Traceback (most recent call last):
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 364, in connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 508, in connect
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/cli/commands/scheduler_command.py", line 55, in scheduler
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/jobs/base_job.py", line 248, in run
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2166, in merge
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2244, in _merge
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 1018, in get
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 1135, in _get_impl
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 286, in load_on_pk_identity
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3490, in one
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3556, in _execute_and_instances
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3571, in _get_bind_args
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1142, in connection
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1150, in _connection_for_bind
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 364, in connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 508, in connect
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/adela/workspace/infra/airflow/myvenv/bin/airflow", line 8, in <module>
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/__main__.py", line 40, in main
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/utils/cli.py", line 89, in wrapper
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/cli/commands/scheduler_command.py", line 55, in scheduler
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/daemon/daemon.py", line 422, in __exit__
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/daemon/daemon.py", line 416, in close
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/lockfile/__init__.py", line 204, in __exit__
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/lockfile/pidlockfile.py", line 103, in release
lockfile.NotLocked: /Users/adela/airflow/airflow-scheduler.pid is not locked
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/daemon/daemon.py", line 416, in close
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/lockfile/__init__.py", line 204, in __exit__
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/lockfile/pidlockfile.py", line 103, in release
lockfile.NotLocked: /Users/adela/airflow/airflow-scheduler.pid is not locked
