2021-03-26 11:40:14,208 INFO - Starting the scheduler
2021-03-26 11:40:14,209 INFO - Processing each file at most -1 times
2021-03-26 11:40:14,218 INFO - Launched DagFileProcessorManager with pid: 67700
2021-03-26 11:40:14,219 INFO - Resetting orphaned tasks for active dag runs
2021-03-26 11:45:14,612 INFO - Resetting orphaned tasks for active dag runs
2021-03-26 11:50:15,312 INFO - Resetting orphaned tasks for active dag runs
2021-03-26 11:51:48,094 INFO - 4 tasks up for execution:
	<TaskInstance: example_bash_operator.runme_0 2021-03-24 00:00:00+00:00 [scheduled]>
	<TaskInstance: example_bash_operator.runme_1 2021-03-24 00:00:00+00:00 [scheduled]>
	<TaskInstance: example_bash_operator.runme_2 2021-03-24 00:00:00+00:00 [scheduled]>
	<TaskInstance: example_bash_operator.also_run_this 2021-03-24 00:00:00+00:00 [scheduled]>
2021-03-26 11:51:48,096 INFO - Figuring out tasks to run in Pool(name=default_pool) with 128 open slots and 4 task instances ready to be queued
2021-03-26 11:51:48,096 INFO - DAG example_bash_operator has 0/16 running and queued tasks
2021-03-26 11:51:48,097 INFO - DAG example_bash_operator has 1/16 running and queued tasks
2021-03-26 11:51:48,097 INFO - DAG example_bash_operator has 2/16 running and queued tasks
2021-03-26 11:51:48,098 INFO - DAG example_bash_operator has 3/16 running and queued tasks
2021-03-26 11:51:48,098 INFO - Setting the following tasks to queued state:
	<TaskInstance: example_bash_operator.runme_0 2021-03-24 00:00:00+00:00 [scheduled]>
	<TaskInstance: example_bash_operator.runme_1 2021-03-24 00:00:00+00:00 [scheduled]>
	<TaskInstance: example_bash_operator.runme_2 2021-03-24 00:00:00+00:00 [scheduled]>
	<TaskInstance: example_bash_operator.also_run_this 2021-03-24 00:00:00+00:00 [scheduled]>
2021-03-26 11:51:48,100 INFO - Sending TaskInstanceKey(dag_id='example_bash_operator', task_id='runme_0', execution_date=datetime.datetime(2021, 3, 24, 0, 0, tzinfo=Timezone('UTC')), try_number=1) to executor with priority 3 and queue default
2021-03-26 11:51:48,100 INFO - Adding to queue: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_0', '2021-03-24T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', '/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py']
2021-03-26 11:51:48,101 INFO - Sending TaskInstanceKey(dag_id='example_bash_operator', task_id='runme_1', execution_date=datetime.datetime(2021, 3, 24, 0, 0, tzinfo=Timezone('UTC')), try_number=1) to executor with priority 3 and queue default
2021-03-26 11:51:48,101 INFO - Adding to queue: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_1', '2021-03-24T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', '/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py']
2021-03-26 11:51:48,102 INFO - Sending TaskInstanceKey(dag_id='example_bash_operator', task_id='runme_2', execution_date=datetime.datetime(2021, 3, 24, 0, 0, tzinfo=Timezone('UTC')), try_number=1) to executor with priority 3 and queue default
2021-03-26 11:51:48,102 INFO - Adding to queue: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_2', '2021-03-24T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', '/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py']
2021-03-26 11:51:48,103 INFO - Sending TaskInstanceKey(dag_id='example_bash_operator', task_id='also_run_this', execution_date=datetime.datetime(2021, 3, 24, 0, 0, tzinfo=Timezone('UTC')), try_number=1) to executor with priority 2 and queue default
2021-03-26 11:51:48,103 INFO - Adding to queue: ['airflow', 'tasks', 'run', 'example_bash_operator', 'also_run_this', '2021-03-24T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', '/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py']
2021-03-26 11:51:48,105 INFO - Executing command: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_0', '2021-03-24T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', '/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py']
2021-03-26 11:51:49,945 INFO - Executing command: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_1', '2021-03-24T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', '/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py']
2021-03-26 11:51:51,872 INFO - Executing command: ['airflow', 'tasks', 'run', 'example_bash_operator', 'runme_2', '2021-03-24T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', '/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py']
2021-03-26 11:51:53,936 INFO - Executing command: ['airflow', 'tasks', 'run', 'example_bash_operator', 'also_run_this', '2021-03-24T00:00:00+00:00', '--local', '--pool', 'default_pool', '--subdir', '/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py']
2021-03-26 11:51:54,960 INFO - Executor reports execution of example_bash_operator.runme_0 execution_date=2021-03-24 00:00:00+00:00 exited with status success for try_number 1
2021-03-26 11:51:54,961 INFO - Executor reports execution of example_bash_operator.runme_1 execution_date=2021-03-24 00:00:00+00:00 exited with status success for try_number 1
2021-03-26 11:51:54,961 INFO - Executor reports execution of example_bash_operator.runme_2 execution_date=2021-03-24 00:00:00+00:00 exited with status success for try_number 1
2021-03-26 11:51:54,962 INFO - Executor reports execution of example_bash_operator.also_run_this execution_date=2021-03-24 00:00:00+00:00 exited with status success for try_number 1
2021-03-26 11:55:15,983 INFO - Resetting orphaned tasks for active dag runs
2021-03-26 11:55:15,988 INFO - Reset the following 1 orphaned TaskInstances:
	<TaskInstance: example_bash_operator.run_after_loop 2021-03-24 00:00:00+00:00 [scheduled]>
2021-03-26 11:57:12,164 ERROR - Exception when executing SchedulerJob._run_scheduler_loop
Traceback (most recent call last):
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 364, in connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 508, in connect
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 1280, in _execute
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 1382, in _run_scheduler_loop
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 1478, in _do_scheduling
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 1581, in _create_dagruns_for_dags
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/tenacity/__init__.py", line 390, in __iter__
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/tenacity/__init__.py", line 368, in iter
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/tenacity/__init__.py", line 186, in reraise
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/airflow/jobs/scheduler_job.py", line 1590, in _create_dagruns_for_dags
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3373, in all
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3556, in _execute_and_instances
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3571, in _get_bind_args
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1142, in connection
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1150, in _connection_for_bind
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 364, in connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
  File "/Users/adela/workspace/infra/airflow/myvenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 508, in connect
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2021-03-26 11:57:13,180 INFO - Sending Signals.SIGTERM to GPID 67700
2021-03-26 11:57:13,398 INFO - Process psutil.Process(pid=67700, status='terminated', exitcode=0, started='11:40:14') (67700) terminated with exit code 0
2021-03-26 11:57:13,399 INFO - Exited execute loop
